metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-06-14T07:41:19Z"
  generation: 1
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"cc457d47-5752-4b9f-a999-0f0fe53313a8"}: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app.kubernetes.io/name: {}
              f:app.kubernetes.io/part-of: {}
              f:skupper.io/component: {}
          f:spec:
            f:containers:
              k:{"name":"flow-collector"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"FLOW_USERS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"OWNER_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"OWNER_UID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_NAMESPACE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_ROUTER_MODE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_SERVICE_ACCOUNT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_SITE_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_SITE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:runAsNonRoot: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/etc/console-users/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/etc/messaging/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/etc/service-controller/console/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
              k:{"name":"service-controller"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"FLOW_USERS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"METRICS_USERS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"OWNER_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"OWNER_UID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_NAMESPACE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_ROUTER_MODE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_SERVICE_ACCOUNT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_SITE_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SKUPPER_SITE_NAME"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8010,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":8080,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":8081,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources: {}
                f:securityContext:
                  .: {}
                  f:runAsNonRoot: {}
                f:startupProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/etc/console-users/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/etc/messaging/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/etc/service-controller/certs/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/etc/service-controller/console/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext:
              .: {}
              f:runAsNonRoot: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"skupper-claims-server"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:secretName: {}
              k:{"name":"skupper-console-certs"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:secretName: {}
              k:{"name":"skupper-console-users"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:secretName: {}
              k:{"name":"skupper-local-client"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:secretName: {}
    manager: skupper
    operation: Update
    time: "2023-06-14T07:41:19Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2023-06-14T07:42:04Z"
  name: skupper-service-controller
  namespace: public1
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: skupper-site
    uid: cc457d47-5752-4b9f-a999-0f0fe53313a8
  resourceVersion: "648"
  uid: 96a8f660-9e11-4876-84c2-d12282ce4a2c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      skupper.io/component: service-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: skupper-service-controller
        app.kubernetes.io/part-of: skupper
        skupper.io/component: service-controller
    spec:
      containers:
      - env:
        - name: SKUPPER_NAMESPACE
          value: public1
        - name: SKUPPER_SITE_NAME
          value: public1
        - name: SKUPPER_SITE_ID
          value: cc457d47-5752-4b9f-a999-0f0fe53313a8
        - name: SKUPPER_SERVICE_ACCOUNT
          value: skupper-router
        - name: SKUPPER_ROUTER_MODE
          value: interior
        - name: OWNER_NAME
          value: skupper-router
        - name: OWNER_UID
          value: 02b6ec3b-7842-4391-9312-ef631ece6438
        - name: FLOW_USERS
          value: /etc/console-users
        - name: METRICS_USERS
          value: /etc/console-users
        image: quay.io/skupper/service-controller:1.4.0-rc3
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8182
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: service-controller
        ports:
        - containerPort: 8010
          name: metrics
          protocol: TCP
        - containerPort: 8080
          name: rest-api
          protocol: TCP
        - containerPort: 8081
          name: claims
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8182
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsNonRoot: true
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /healthz
            port: 8182
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/console-users/
          name: skupper-console-users
        - mountPath: /etc/service-controller/certs/
          name: skupper-claims-server
        - mountPath: /etc/service-controller/console/
          name: skupper-console-certs
        - mountPath: /etc/messaging/
          name: skupper-local-client
      - env:
        - name: SKUPPER_NAMESPACE
          value: public1
        - name: SKUPPER_SITE_NAME
          value: public1
        - name: SKUPPER_SITE_ID
          value: cc457d47-5752-4b9f-a999-0f0fe53313a8
        - name: SKUPPER_SERVICE_ACCOUNT
          value: skupper-router
        - name: SKUPPER_ROUTER_MODE
          value: interior
        - name: OWNER_NAME
          value: skupper-router
        - name: OWNER_UID
          value: 02b6ec3b-7842-4391-9312-ef631ece6438
        - name: FLOW_USERS
          value: /etc/console-users
        image: quay.io/skupper/flow-collector:1.4.0-rc3
        imagePullPolicy: Always
        name: flow-collector
        resources: {}
        securityContext:
          runAsNonRoot: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/console-users/
          name: skupper-console-users
        - mountPath: /etc/service-controller/console/
          name: skupper-console-certs
        - mountPath: /etc/messaging/
          name: skupper-local-client
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: skupper-service-controller
      serviceAccountName: skupper-service-controller
      terminationGracePeriodSeconds: 30
      volumes:
      - name: skupper-console-users
        secret:
          defaultMode: 420
          secretName: skupper-console-users
      - name: skupper-claims-server
        secret:
          defaultMode: 420
          secretName: skupper-claims-server
      - name: skupper-console-certs
        secret:
          defaultMode: 420
          secretName: skupper-console-certs
      - name: skupper-local-client
        secret:
          defaultMode: 420
          secretName: skupper-local-client
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-14T07:42:04Z"
    lastUpdateTime: "2023-06-14T07:42:04Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-14T07:41:19Z"
    lastUpdateTime: "2023-06-14T07:42:04Z"
    message: ReplicaSet "skupper-service-controller-566f77f46" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
